openapi: "3.0.0"
info:
  title: Mock API
  version: "1.0.0"
paths:
  /users/{id}:
    get:
      summary: Get user info
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        "404":
          description: User not found
